# Generated by Django 6.0 on 2026-04-18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginotpchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pending_username', models.CharField(max_length=150)),
                ('pending_email', models.EmailField(max_length=254)),
                ('pending_password_hash', models.CharField(max_length=255)),
                ('code_hash', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['pending_email', 'created_at'], name='users_regis_pending_6a7ad8_idx'),
                    models.Index(fields=['pending_username', 'created_at'], name='users_regis_pending_931e50_idx'),
                    models.Index(fields=['expires_at', 'is_used'], name='users_regis_expires_4065bb_idx'),
                ],
            },
        ),
    ]
  