# Generated by Django 6.0.2 on 2026-03-27 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField()),
                ('province', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('nearest_city', models.CharField(blank=True, max_length=120)),
                ('altitude_m', models.PositiveIntegerField(default=0)),
                ('best_season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all', 'All Season')], default='all', max_length=20)),
                ('tour_type', models.CharField(choices=[('trekking', 'Trekking'), ('traveling', 'Traveling'), ('both', 'Both')], default='traveling', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('suggested_duration_days', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfflineMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('file_url', models.URLField()),
                ('version', models.CharField(default='v1', max_length=20)),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_maps', to='tourism.destination')),
            ],
            options={
                'ordering': ['destination__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe')], default='standard', max_length=20)),
                ('tour_type', models.CharField(choices=[('trekking', 'Trekking'), ('traveling', 'Traveling')], default='traveling', max_length=20)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('max_group_size', models.PositiveIntegerField(default=1)),
                ('price_npr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('includes', models.TextField(blank=True)),
                ('excludes', models.TextField(blank=True)),
                ('itinerary_overview', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_packages', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tourism.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_date', models.DateField()),
                ('total_seats', models.PositiveIntegerField(default=1)),
                ('available_seats', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tourism.package')),
            ],
            options={
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('travelers_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('special_request', models.TextField(blank=True)),
                ('total_amount_npr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tourism.package')),
                ('departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tourism.packagedeparture')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('cash', 'Cash')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('amount_npr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tourism.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='tourism.booking')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.destination')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['name'], name='tourism_des_name_205248_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['province', 'district'], name='tourism_des_provinc_0ad687_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['best_season', 'tour_type'], name='tourism_des_best_se_ebb348_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offlinemap',
            unique_together={('destination', 'title', 'version')},
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['package_type', 'tour_type'], name='tourism_pac_package_099f98_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['price_npr'], name='tourism_pac_price_n_4e64f5_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active'], name='tourism_pac_is_acti_448059_idx'),
        ),
        migrations.AddIndex(
            model_name='packagedeparture',
            index=models.Index(fields=['departure_date', 'status'], name='tourism_pac_departu_5dc0a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packagedeparture',
            unique_together={('package', 'departure_date')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='tourism_boo_status_02f297_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='tourism_boo_booking_269a50_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'status'], name='tourism_pay_method_4db958_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='tourism_pay_transac_11557a_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_to_5'),
        ),
    ]
