# Generated by Django 6.0.2 on 2026-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('deluxe', 'Deluxe')], default='standard', max_length=20),
        ),
    ]
